### ISSUE TITLE
wpilib-nt-client crash on robot connect

### ISSUE THREAD

**Issue by AdamBusch** [rakusan2/FRC-NT-Client#5]
Connecting to a robot from a new project crashes with an error  about 50% of the time and point's to
index.js:83 or index.js:50
`                let val = TypesFrom[entry.typeID](buf, off);`
I am using the FRC Custom dashboard to connect.
![screenshot_1](https://user-images.githubusercontent.com/11702435/31738179-6b6c600c-b40f-11e7-9c66-0fd261e97001.png)

**Comment by rakusan2** [comment]
My current theory is that this error happens because the packet has been split which is something that 1.x is unable to deal with.
2.x should have a fix for this but it is going to take about 2 weeks to finish

**Comment by rakusan2** [comment]
Sorry for the delay, with all the work I had forgotten on this.
Due to this I am postponing 2.x and and made a quick fix for this issue in 1.3.0
I currently only have access to a half working simulator so I am going to wait till I get a response from someone before closing this but as of now it has worked in that simulator
